# ISSUE TRACKER: JIRA
issue_tracker: "jira"
jira:
  server_url: "https://jira.salsitasoft.com"
  project_key: "SF"
# CODE REVIEW TOOL: Review Board
code_review_tool: "review_board"
review_board:
  server_url: "https://review.salsitasoft.com"
